//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bpmn20XmlValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bpmn20XmlValidator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;	
        ///	xmlns=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;
        ///	xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot;
        ///	targetNamespace=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;&gt;
        ///
        ///	&lt;xsd:import namespace=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; schemaLocation=&quot;BPMNDI.xsd&quot;/&gt;
        ///	&lt;xsd:include schemaLocation=&quot;Semantic.xsd&quot;/&gt;
        ///
        ///	&lt;xsd:element name=&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BPMN20 {
            get {
                return ResourceManager.GetString("BPMN20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; targetNamespace=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot;  elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xsd:import namespace=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; schemaLocation=&quot;DC.xsd&quot; /&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.om [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BPMNDI {
            get {
                return ResourceManager.GetString("BPMNDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; targetNamespace=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xsd:element name=&quot;Font&quot; type=&quot;dc:Font&quot; /&gt;
        ///	&lt;xsd:element name=&quot;Point&quot; type=&quot;dc:Point&quot; /&gt;
        ///	&lt;xsd:element name=&quot;Bounds&quot; type=&quot;dc:Bounds&quot; /&gt;
        ///	
        ///	&lt;xsd:complexType name=&quot;Font&quot;&gt;
        ///		&lt;xsd:attribute name=&quot;name&quot; type=&quot;xsd:string&quot; /&gt;
        ///		&lt;xsd:attr [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; targetNamespace=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xsd:import namespace=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; schemaLocation=&quot;DC.xsd&quot; /&gt;
        ///	
        ///	&lt;xsd:element name=&quot;DiagramElement&quot; type=&quot;di:DiagramElement&quot; /&gt;
        ///	&lt;xsd:element name=&quot;Diagram&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DI {
            get {
                return ResourceManager.GetString("DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;
        ///	xmlns=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; 
        ///	xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///	targetNamespace=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;&gt;
        ///	
        ///	&lt;xsd:element name=&quot;activity&quot; type=&quot;tActivity&quot;/&gt;
        ///	&lt;xsd:complexType name=&quot;tActivity&quot; abstract=&quot;true&quot;&gt;
        ///		&lt;xsd:complexContent&gt;
        ///			&lt;xsd:extension base=&quot;tFlowNode&quot;&gt;
        ///				&lt;xsd:sequence&gt;
        ///					&lt;xsd:element ref=&quot;ioSpecification [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Semantic {
            get {
                return ResourceManager.GetString("Semantic", resourceCulture);
            }
        }
    }
}
